// import { Student } from './student.model';

// export const MOCKSTUDENTS: Student[] = [
//   {
//     id: '1',
//     firstName: 'Ava',
//     lastName: 'Johnson',
//     age: 10,
//     level: 'Beginner',
//     parentName: 'Lisa Johnson',
//     parentRelationship: 'Mother',
//     parentPhone: '555-987-6543',
//     parentEmail: 'lisa.johnson@example.com',
//   },
//   {
//     id: '2',
//     firstName: 'Leo',
//     lastName: 'Martinez',
//     age: 11,
//     level: 'Intermediate',
//     parentName: 'Carlos Martinez',
//     parentRelationship: 'Father',
//     parentPhone: '555-555-0102',
//     parentEmail: 'carlos.m@example.com',
//   },
//   {
//     id: '3',
//     firstName: 'Maya',
//     lastName: 'Chen',
//     age: 9,
//     level: 'Beginner',
//     parentName: 'Grace Chen',
//     parentRelationship: 'Guardian',
//     parentPhone: '555-222-3345',
//     parentEmail: 'grace.chen@example.com',
//   },
//   {
//     id: '4',
//     firstName: 'Ethan',
//     lastName: 'Williams',
//     age: 12,
//     level: 'Advanced',
//     parentName: 'Sarah Williams',
//     parentRelationship: 'Mother',
//     parentPhone: '555-666-7799',
//     parentEmail: 'sarah.williams@example.com',
//   },
//   {
//     id: '5',
//     firstName: 'Sofia',
//     lastName: 'Brown',
//     age: 8,
//     level: 'Beginner',
//     parentName: 'Michael Brown',
//     parentRelationship: 'Father',
//     parentPhone: '555-111-2234',
//     parentEmail: 'michael.brown@example.com',
//   },
//   {
//     id: '6',
//     firstName: 'Noah',
//     lastName: 'Garcia',
//     age: 10,
//     level: 'Intermediate',
//     parentName: 'Maria Garcia',
//     parentRelationship: 'Mother',
//     parentPhone: '555-444-5566',
//     parentEmail: 'maria.garcia@example.com'
//   },
//   {
//     id: '7',
//     firstName: 'Olivia',
//     lastName: 'Davis',
//     age: 11,
//     level: 'Advanced',
//     parentName: 'James Davis',
//     parentRelationship: 'Father',
//     parentPhone: '555-333-7788',
//     parentEmail: 'james.davis@example.com'
//   }
// ];
